USE cms_db;

INSERT INTO lessons (course_id, title, description, content_type, content, duration_minutes, order_num) VALUES
-- Course 7: Python Programming
(7, 'Python Fundamentals', 'Introduction to Python programming basics', 'article', '<h2>Welcome to Python!</h2><p>Python is a high-level, interpreted programming language known for its simplicity and readability.</p><h3>Why Python?</h3><ul><li>Easy to learn syntax</li><li>Versatile - web, data science, AI, automation</li><li>Large community support</li><li>Extensive libraries</li></ul><h3>Your First Python Program</h3><pre>print("Hello, World!")</pre><h3>Variables</h3><pre>name = "Alice"\nage = 25\nis_student = True\nprice = 19.99</pre>', 30, 1),
(7, 'Control Flow and Functions', 'Learn loops, conditionals and functions in Python', 'article', '<h2>Control Flow</h2><p>Python uses indentation to define code blocks.</p><h3>If-Else</h3><pre>if age >= 18:\n    print("Adult")\nelse:\n    print("Minor")</pre><h3>Loops</h3><pre># For loop\nfor i in range(5):\n    print(i)\n\n# While loop\ncount = 0\nwhile count < 5:\n    print(count)\n    count += 1</pre><h3>Functions</h3><pre>def greet(name):\n    return f"Hello, {name}!"\n\nresult = greet("Python")\nprint(result)</pre>', 45, 2),
(7, 'Data Structures in Python', 'Lists, dictionaries, sets and tuples', 'article', '<h2>Python Data Structures</h2><h3>Lists</h3><pre>fruits = ["apple", "banana", "cherry"]\nfruits.append("orange")\nprint(fruits[0])</pre><h3>Dictionaries</h3><pre>person = {\n    "name": "Alice",\n    "age": 25,\n    "city": "NYC"\n}\nprint(person["name"])</pre><h3>Sets and Tuples</h3><pre>colors = {"red", "green", "blue"}\ncoordinates = (10, 20, 30)</pre>', 50, 3),

-- Course 8: Data Structures
(8, 'Arrays and Linked Lists', 'Fundamental data structures basics', 'article', '<h2>Arrays</h2><p>Arrays store elements in contiguous memory locations.</p><h3>Advantages</h3><ul><li>O(1) random access</li><li>Cache-friendly</li><li>Simple implementation</li></ul><h3>Disadvantages</h3><ul><li>Fixed size</li><li>Expensive insertion/deletion</li></ul><h2>Linked Lists</h2><p>Nodes connected through pointers.</p><h3>Singly Linked List</h3><pre>class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None</pre><h3>Operations</h3><ul><li>Insert: O(1) at head</li><li>Delete: O(1) at head</li><li>Search: O(n)</li></ul>', 55, 1),
(8, 'Stacks and Queues', 'LIFO and FIFO data structures', 'article', '<h2>Stack (LIFO)</h2><p>Last In, First Out - like a stack of plates.</p><pre>stack = []\nstack.append(1)  # push\nstack.append(2)\ntop = stack.pop()  # pop - returns 2</pre><h3>Applications</h3><ul><li>Function calls</li><li>Undo operations</li><li>Expression evaluation</li></ul><h2>Queue (FIFO)</h2><p>First In, First Out - like a real queue.</p><pre>from collections import deque\nqueue = deque()\nqueue.append(1)\nqueue.append(2)\nfirst = queue.popleft()  # returns 1</pre><h3>Applications</h3><ul><li>Task scheduling</li><li>BFS traversal</li></ul>', 50, 2),
(8, 'Trees and Graphs', 'Hierarchical and network data structures', 'article', '<h2>Trees</h2><p>A hierarchical structure with nodes and edges.</p><h3>Binary Tree</h3><pre>class TreeNode:\n    def __init__(self, val):\n        self.val = val\n        self.left = None\n        self.right = None</pre><h3>Tree Types</h3><ul><li>Binary Search Tree (BST)</li><li>AVL Trees</li><li>Heap</li></ul><h2>Graphs</h2><p>Nodes connected by edges - can be directed/undirected.</p><pre>graph = {\n    "A": ["B", "C"],\n    "B": ["A", "D"],\n    "C": ["A", "D"],\n    "D": ["B", "C"]\n}</pre><h3>Graph Traversal</h3><ul><li>BFS - Queue based</li><li>DFS - Stack/Recursion based</li></ul>', 60, 3),

-- Course 11: Database Management Systems
(11, 'Introduction to Databases', 'What is a DBMS and why we need it', 'article', '<h2>What is a Database?</h2><p>A structured collection of data stored electronically.</p><h3>DBMS (Database Management System)</h3><ul><li>Software to create and manage databases</li><li>Examples: MySQL, PostgreSQL, Oracle</li></ul><h3>Types of Databases</h3><ul><li><strong>Relational (SQL)</strong> - MySQL, PostgreSQL, SQL Server</li><li><strong>NoSQL</strong> - MongoDB, Redis, Cassandra</li></ul><h3>Key Terms</h3><ul><li><strong>Table</strong> - Collection of rows</li><li><strong>Row/Tuple</strong> - A single record</li><li><strong>Column/Field</strong> - An attribute</li><li><strong>Primary Key</strong> - Unique identifier</li></ul>', 35, 1),
(11, 'SQL Basics', 'Learn SELECT, INSERT, UPDATE, DELETE', 'article', '<h2>SQL Commands</h2><h3>SELECT - Retrieve Data</h3><pre>SELECT * FROM students;\nSELECT name, email FROM students WHERE age > 18;</pre><h3>INSERT - Add Data</h3><pre>INSERT INTO students (name, email, age)\nVALUES ("Alice", "alice@email.com", 20);</pre><h3>UPDATE - Modify Data</h3><pre>UPDATE students\nSET age = 21\nWHERE id = 1;</pre><h3>DELETE - Remove Data</h3><pre>DELETE FROM students WHERE id = 1;</pre>', 45, 2),
(11, 'Joins and Relationships', 'Connecting data across multiple tables', 'article', '<h2>Relationships</h2><ul><li><strong>One-to-One</strong> - A user has one profile</li><li><strong>One-to-Many</strong> - A teacher has many students</li><li><strong>Many-to-Many</strong> - Students enroll in many courses</li></ul><h2>SQL Joins</h2><h3>INNER JOIN</h3><pre>SELECT students.name, courses.title\nFROM students\nINNER JOIN enrollments ON students.id = enrollments.student_id\nINNER JOIN courses ON enrollments.course_id = courses.id;</pre><h3>Types of Joins</h3><ul><li>LEFT JOIN</li><li>RIGHT JOIN</li><li>FULL OUTER JOIN</li></ul>', 50, 3),

-- Course 12: React JS Development
(12, 'React Fundamentals', 'Introduction to React and component-based architecture', 'article', '<h2>What is React?</h2><p>React is a JavaScript library for building user interfaces, developed by Facebook.</p><h3>Why React?</h3><ul><li>Component-based architecture</li><li>Virtual DOM for performance</li><li>Reusable components</li><li>Strong community</li></ul><h3>Your First Component</h3><pre>import React from "react";\n\nfunction HelloWorld() {\n    return <h1>Hello, World!</h1>;\n}\n\nexport default HelloWorld;</pre><h3>JSX</h3><p>JSX lets you write HTML-like syntax in JavaScript.</p><pre>const element = <h1>Hello, React!</h1>;</pre>', 40, 1),
(12, 'State and Props', 'Managing data in React components', 'article', '<h2>Props</h2><p>Props are read-only data passed from parent to child.</p><pre>function Welcome(props) {\n    return <h1>Hello, {props.name}!</h1>;\n}\n\n<Welcome name="Alice" /></pre><h2>State</h2><p>State is mutable data managed within a component.</p><pre>import { useState } from "react";\n\nfunction Counter() {\n    const [count, setCount] = useState(0);\n    \n    return (\n        <div>\n            <p>Count: {count}</p>\n            <button onClick={() => setCount(count + 1)}>\n                Increment\n            </button>\n        </div>\n    );\n}</pre>', 45, 2),
(12, 'React Hooks Deep Dive', 'useEffect, useContext, and custom hooks', 'article', '<h2>useEffect Hook</h2><p>Handle side effects like data fetching, subscriptions.</p><pre>import { useEffect } from "react";\n\nuseEffect(() => {\n    fetchData();\n}, []); // Empty deps = runs once</pre><h2>useContext</h2><p>Share state across components without prop drilling.</p><pre>const ThemeContext = React.createContext();\n\nfunction App() {\n    return (\n        <ThemeContext.Provider value="dark">\n            <Component />\n        </ThemeContext.Provider>\n    );\n}</pre><h2>Custom Hooks</h2><pre>function useWindowSize() {\n    const [size, setSize] = useState(window.innerWidth);\n    // ... implementation\n    return size;\n}</pre>', 55, 3),

-- Course 13: Node.js Backend Development
(13, 'Node.js Introduction', 'Server-side JavaScript runtime', 'article', '<h2>What is Node.js?</h2><p>Node.js is a JavaScript runtime built on Chrome''s V8 engine that executes JavaScript on the server.</p><h3>Features</h3><ul><li>Non-blocking I/O</li><li>Event-driven architecture</li><li>NPM package ecosystem</li><li>Single-threaded event loop</li></ul><h3>Your First Server</h3><pre>const http = require("http");\n\nconst server = http.createServer((req, res) => {\n    res.writeHead(200, {"Content-Type": "text/html"});\n    res.end("Hello, Node.js!");\n});\n\nserver.listen(3000, () => {\n    console.log("Server running on port 3000");\n});</pre>', 35, 1),
(13, 'Express.js Framework', 'Building RESTful APIs with Express', 'article', '<h2>Express.js</h2><p>Minimal and flexible Node.js web application framework.</p><h3>Setup</h3><pre>npm install express</pre><h3>Basic App</h3><pre>const express = require("express");\nconst app = express();\n\napp.get("/", (req, res) => {\n    res.send("Hello, Express!");\n});\n\napp.listen(3000);</pre><h3>RESTful Routes</h3><pre>app.get("/api/users", getUsers);\napp.post("/api/users", createUser);\napp.put("/api/users/:id", updateUser);\napp.delete("/api/users/:id", deleteUser);</pre>', 50, 2),
(13, 'Middleware and Error Handling', 'Express middleware patterns', 'article', '<h2>Middleware</h2><p>Functions that execute during the request-response cycle.</p><h3>Types of Middleware</h3><ul><li>Application-level (app.use)</li><li>Router-level</li><li>Error-handling</li><li>Built-in</li><li>Third-party</li></ul><h3>Examples</h3><pre>// Logging middleware\napp.use((req, res, next) => {\n    console.log(`${req.method} ${req.path}`);\n    next();\n});\n\n// Error handler\napp.use((err, req, res, next) => {\n    console.error(err.stack);\n    res.status(500).send("Something broke!");\n});</pre><h3>Authentication Middleware</h3><pre>function auth(req, res, next) {\n    if (req.headers.authorization) {\n        next();\n    } else {\n        res.status(401).send("Unauthorized");\n    }\n}</pre>', 55, 3),

-- Course 14: Machine Learning Basics
(14, 'Introduction to Machine Learning', 'What is ML and types of learning', 'article', '<h2>What is Machine Learning?</h2><p>A subset of AI where computers learn patterns from data without being explicitly programmed.</p><h3>Types of Machine Learning</h3><ul><li><strong>Supervised Learning</strong> - Learn from labeled data (classification, regression)</li><li><strong>Unsupervised Learning</strong> - Find patterns in unlabeled data (clustering, dimensionality reduction)</li><li><strong>Reinforcement Learning</strong> - Learn through trial and error</li></ul><h3>Applications</h3><ul><li>Email spam filtering</li><li>Recommendation systems</li><li>Image recognition</li><li>Speech assistants</li></ul>', 40, 1),
(14, 'Supervised Learning', 'Classification and Regression algorithms', 'article', '<h2>Classification</h2><p>Predicting discrete categories.</p><h3>Algorithms</h3><ul><li>Linear Regression for continuous</li><li>Logistic Regression for binary</li><li>Decision Trees</li><li>Random Forest</li><li>Support Vector Machines</li></ul><h3>Example: Logistic Regression</h3><pre>from sklearn.linear_model import LogisticRegression\n\nmodel = LogisticRegression()\nmodel.fit(X_train, y_train)\npredictions = model.predict(X_test)</pre><h2>Regression</h2><p>Predicting continuous numerical values.</p><pre>from sklearn.linear_model import LinearRegression\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprice = model.predict([[1200]])</pre>', 55, 2),
(14, 'Model Evaluation and Overfitting', 'Measuring model performance', 'article', '<h2>Evaluation Metrics</h2><h3>Classification Metrics</h3><ul><li><strong>Accuracy</strong> - Correct predictions / Total</li><li><strong>Precision</strong> - TP / (TP + FP)</li><li><strong>Recall</strong> - TP / (TP + FN)</li><li><strong>F1 Score</strong> - Harmonic mean of precision/recall</li></ul><h3>Regression Metrics</h3><ul><li><strong>Mean Absolute Error (MAE)</strong></li><li><strong>Mean Squared Error (MSE)</strong></li><li><strong>R² Score</strong></li></ul><h2>Overfitting vs Underfitting</h2><ul><li><strong>Overfitting</strong> - Model memorizes training data, fails on new data</li><li><strong>Underfitting</strong> - Model is too simple to capture patterns</li></ul><h3>Solutions</h3><ul><li>Cross-validation</li><li>Regularization</li><li>More training data</li></ul>', 50, 3),

-- Course 15: UI UX Design Fundamentals
(15, 'Introduction to UI Design', 'Principles of visual interface design', 'article', '<h2>What is UI Design?</h2><p>User Interface design focuses on anticipating what users might need to do and ensuring the interface has elements that are easy to access and use.</p><h3>Key Principles</h3><ul><li><strong>Hierarchy</strong> - Visual arrangement to show importance</li><li><strong>Contrast</strong> - Make important elements stand out</li><li><strong>Repetition</strong> - Consistent use of colors, fonts, patterns</li><li><strong>Alignment</strong> - Clear visual connection between elements</li></ul><h3>Color Theory</h3><ul><li>Primary colors (red, blue, yellow)</li><li>Secondary colors</li><li>Complementary colors (opposite on wheel)</li></ul>', 35, 1),
(15, 'UX Research and Wireframing', 'Understanding users and planning layouts', 'article', '<h2>What is UX Design?</h2><p>User Experience design is the process of creating products that provide meaningful experiences.</p><h3>UX Research Methods</h3><ul><li><strong>User Interviews</strong> - Direct conversations</li><li><strong>Surveys</strong> - Quantitative data</li><li><strong>Usability Testing</strong> - Observing users</li><li><strong>Competitor Analysis</strong> - Benchmarking</li></ul><h3>Wireframing</h3><p>Low-fidelity skeletal framework of a digital product.</p><h3>Tools</h3><ul><li>Figma</li><li>Sketch</li><li>Adobe XD</li><li>Balsamiq</li></ul>', 45, 2),
(15, 'Prototyping and Testing', 'From wireframes to interactive prototypes', 'article', '<h2>Prototyping</h2><p>Interactive representation of your final product.</p><h3>Types</h3><ul><li><strong>Low-fidelity</strong> - Paper sketches, wireframes</li><li><strong>Mid-fidelity</strong> - Digital wireframes</li><li><strong>High-fidelity</strong> - Fully interactive, looks like final product</li></ul><h2>Usability Testing</h2><p>Evaluating a product by testing it with representative users.</p><h3>Testing Process</h3><ol><li>Define test objectives</li><li>Recruit participants</li><li>Conduct sessions</li><li>Analyze results</li><li>Iterate and improve</li></ol>', 50, 3),

-- Course 16: Cyber Security Fundamentals
(16, 'Introduction to Cyber Security', 'Understanding threats and protection', 'article', '<h2>What is Cyber Security?</h2><p>The practice of protecting systems, networks, and programs from digital attacks.</p><h3>Core Principles (CIA Triad)</h3><ul><li><strong>Confidentiality</strong> - Only authorized access</li><li><strong>Integrity</strong> - Data is accurate and trustworthy</li><li><strong>Availability</strong> - Systems accessible when needed</li></ul><h3>Common Threats</h3><ul><li>Malware (viruses, ransomware)</li><li>Phishing</li><li>Man-in-the-middle attacks</li><li>Denial of Service (DoS)</li><li>SQL Injection</li></ul>', 40, 1),
(16, 'Network Security', 'Securing network infrastructure', 'article', '<h2>Network Security</h2><p>Protecting network infrastructure and data as it travels across networks.</p><h3>Security Layers</h3><ul><li><strong>Firewall</strong> - Filters incoming/outgoing traffic</li><li><strong>VPN</strong> - Encrypted connection over internet</li><li><strong>IDS/IPS</strong> - Intrusion detection/prevention</li></ul><h3>Types of Firewalls</h3><ul><li>Packet filtering</li><li>Stateful inspection</li><li>Application-layer</li><li>Next-generation</li></ul><h3>Best Practices</h3><ul><li>Use strong passwords</li><li>Enable two-factor authentication</li><li>Keep software updated</li><li>Encrypt sensitive data</li></ul>', 50, 2),
(16, 'Ethical Hacking', 'Penetration testing and vulnerability assessment', 'article', '<h2>What is Ethical Hacking?</h2><p>Authorized simulation of attacks to find vulnerabilities before malicious hackers do.</p><h3>Ethical Hacker Mindset</h3><ul><li>Think like an attacker</li><li>Stay within legal boundaries</li><li>Report all findings</li><li>Never exploit found vulnerabilities</li></ul><h3>Penetration Testing Phases</h3><ol><li><strong>Reconnaissance</strong> - Gather information</li><li><strong>Scanning</strong> - Find open ports, vulnerabilities</li><li><strong>Exploitation</strong> - Attempt to gain access</li><li><strong>Post-exploitation</strong> - Maintain access, escalate privileges</li><li><strong>Reporting</strong> - Document findings</li></ol>', 55, 3),

-- Course 17: Android App Development
(17, 'Introduction to Android Development', 'Setting up Android Studio and first app', 'article', '<h2>What is Android?</h2><p>Linux-based mobile operating system developed by Google.</p><h3>Android Architecture</h3><ul><li>Applications</li><li>Application Framework</li><li>Android Runtime</li><li>Libraries</li><li>HAL (Hardware Abstraction Layer)</li><li>Linux Kernel</li></ul><h3>Your First App</h3><pre>package com.example.myapp\n\nimport android.os.Bundle\nimport androidx.appcompat.app.AppCompatActivity\n\nclass MainActivity : AppCompatActivity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        setContentView(R.layout.activity_main)\n    }\n}</pre>', 40, 1),
(17, 'Activities and Layouts', 'Building user interfaces in Android', 'article', '<h2>Activities</h2><p>A single screen with a user interface (like a window in desktop apps).</p><h3>Activity Lifecycle</h3><pre>onCreate() -> onStart() -> onResume()\n         -> onPause() -> onStop() -> onDestroy()</pre><h2>Layouts</h2><p>XML-based layouts define the UI structure.</p><h3>Common Layouts</h3><ul><li><strong>LinearLayout</strong> - Horizontal or vertical</li><li><strong>RelativeLayout</strong> - Relative positioning</li><li><strong>ConstraintLayout</strong> - Flexible positioning</li><li><strong>RecyclerView</strong> - Scrollable lists</li></ul><pre><LinearLayout\n    android:orientation="vertical"\n    android:layout_width="match_parent"\n    android:layout_height="match_parent"></pre>', 50, 2),
(17, 'Intents and Navigation', 'Communicating between screens', 'article', '<h2>Intents</h2><p>Messaging objects used to request actions from other app components.</p><h3>Explicit Intent</h3><pre>val intent = Intent(this, SecondActivity::class.java)\nintent.putExtra("message", "Hello!")\nstartActivity(intent)</pre><h3>Implicit Intent</h3><pre>val intent = Intent(Intent.ACTION_VIEW)\nintent.data = Uri.parse("https://google.com")\nstartActivity(intent)</pre><h2>Navigation Component</h2><p>Jetpack Navigation component for consistent navigation patterns.</p><pre>val navController = findNavController(R.id.nav_host_fragment)\nnavController.navigate(R.id.action_first_to_second)</pre>', 55, 3),

-- Course 18: Software Engineering
(18, 'Software Development Lifecycle', 'From ideation to deployment', 'article', '<h2>What is SDLC?</h2><p>Software Development Lifecycle is the process of planning, creating, testing, and deploying software.</p><h3>Phases</h3><ol><li><strong>Requirement Analysis</strong> - Gather and analyze requirements</li><li><strong>Design</strong> - System and detailed design</li><li><strong>Implementation</strong> - Coding the software</li><li><strong>Testing</strong> - Finding and fixing bugs</li><li><strong>Deployment</strong> - Releasing to users</li><li><strong>Maintenance</strong> - Ongoing support and updates</li></ol><h3>Popular Models</h3><ul><li>Waterfall (sequential)</li><li>Agile (iterative)</li><li>DevOps (continuous)</li></ul>', 40, 1),
(18, 'Agile and Scrum', 'Modern development methodologies', 'article', '<h2>Agile Manifesto</h2><p>Values and principles for adaptive software development.</p><h3>4 Values</h3><ul><li>Individuals and interactions over processes and tools</li><li>Working software over comprehensive documentation</li><li>Customer collaboration over contract negotiation</li><li>Responding to change over following a plan</li></ul><h2>Scrum Framework</h2><p>Popular Agile framework for managing knowledge work.</p><h3>Roles</h3><ul><li><strong>Product Owner</strong> - Maximizes value</li><li><strong>Scrum Master</strong> - Facilitator</li><li><strong>Development Team</strong> - Self-organizing</li></ul><h3>Events</h3><ul><li>Sprint (2-4 weeks)</li><li>Daily Standup</li><li>Sprint Planning</li><li>Sprint Review</li><li>Retrospective</li></ul>', 50, 2),
(18, 'Version Control with Git', 'Managing code changes and collaboration', 'article', '<h2>What is Git?</h2><p>Distributed version control system for tracking changes in source code.</p><h3>Basic Commands</h3><pre>git init              # Initialize repo\ngit add .             # Stage changes\ngit commit -m "msg"   # Commit\ngit push              # Upload to remote\ngit pull              # Download changes</pre><h3>Branching</h3><pre>git branch feature    # Create branch\ngit checkout feature  # Switch branch\ngit merge feature     # Merge branch</pre><h2>GitHub/GitLab</h2><p>Platforms for hosting Git repositories and collaboration.</p><h3>Pull Requests</h3><p>Request to merge code changes for review before merging.</p>', 45, 3),

-- Course 19: Laravel PHP Framework
(19, 'Laravel Introduction', 'Getting started with Laravel framework', 'article', '<h2>What is Laravel?</h2><p>PHP framework for web application development with elegant, expressive syntax.</p><h3>Why Laravel?</h3><ul><li>Elegant syntax</li><li>Built-in authentication</li><li>ORM (Eloquent)</li><li>Blade templating</li><li>Artisan CLI</li></ul><h3>Installation</h3><pre>composer create-project laravel/laravel myapp\ncd myapp\nphp artisan serve</pre><h3>Directory Structure</h3><ul><li>app/ - Application code</li><li>routes/ - Route definitions</li><li>resources/views/ - Blade templates</li><li>database/ - Migrations, seeders</li></ul>', 40, 1),
(19, 'Routing and Controllers', 'Handling HTTP requests in Laravel', 'article', '<h2>Routing</h2><p>Routes define how URLs are handled by your application.</p><h3>Basic Routes</h3><pre>Route::get("/", function () {\n    return "Hello, World!";\n});\n\nRoute::get("/about", function () {\n    return view("about");\n});</pre><h3>Route Parameters</h3><pre>Route::get("/user/{id}", function ($id) {\n    return "User " . $id;\n});</pre><h2>Controllers</h2><p>Organize request handling logic.</p><pre>class UserController extends Controller\n{\n    public function index() {\n        $users = User::all();\n        return view("users.index", ["users" => $users]);\n    }\n}\n\nRoute::get("/users", [UserController::class, "index"]);</pre>', 50, 2),
(19, 'Eloquent ORM and Migrations', 'Database operations in Laravel', 'article', '<h2>Migrations</h2><p>Database version control for your application.</p><pre>php artisan make:migration create_users_table</pre><h3>Migration Structure</h3><pre>public function up()\n{\n    Schema::create("users", function (Blueprint $table) {\n        $table->id();\n        $table->string("name");\n        $table->string("email")->unique();\n        $table->timestamp("email_verified_at")->nullable();\n        $table->string("password");\n        $table->timestamps();\n    });\n}</pre><h2>Eloquent ORM</h2><p>Active Record implementation for database operations.</p><pre>// Create\nUser::create(["name" => "Alice", "email" => "alice@email.com"]);\n\n// Read\n$user = User::find(1);\n\n// Update\n$user->name = "Bob";\n$user->save();\n\n// Delete\n$user->delete();</pre>', 55, 3),

-- Course 20: Cloud Computing
(20, 'Introduction to Cloud Computing', 'Understanding cloud services and models', 'article', '<h2>What is Cloud Computing?</h2><p>Delivery of computing services over the internet (servers, storage, databases, networking, software, analytics).</p><h3>Cloud Service Models</h3><ul><li><strong>IaaS</strong> - Infrastructure as a Service (AWS EC2, Azure VMs)</li><li><strong>PaaS</strong> - Platform as a Service (Heroku, Google App Engine)</li><li><strong>SaaS</strong> - Software as a Service (Gmail, Dropbox)</li></ul><h3>Deployment Models</h3><ul><li>Public Cloud</li><li>Private Cloud</li><li>Hybrid Cloud</li><li>Community Cloud</li></ul>', 35, 1),
(20, 'Major Cloud Providers', 'AWS, Azure, and Google Cloud overview', 'article', '<h2>Amazon Web Services (AWS)</h2><ul><li>EC2 - Virtual servers</li><li>S3 - Object storage</li><li>RDS - Managed databases</li><li>Lambda - Serverless functions</li></ul><h2>Microsoft Azure</h2><ul><li>Azure Virtual Machines</li><li>Azure Blob Storage</li><li>Azure SQL Database</li><li>Azure Functions</li></ul><h2>Google Cloud Platform</h2><ul><li>Compute Engine</li><li>Cloud Storage</li><li>BigQuery - Data warehouse</li><li>Kubernetes Engine</li></ul><h3>Choosing a Provider</h3><ul><li>Cost</li><li>Services offered</li><li>Region availability</li><li>Compliance needs</li></ul>', 50, 2),
(20, 'Serverless and Cloud Architecture', 'Modern cloud-native development patterns', 'article', '<h2>Serverless Computing</h2><p>Build applications without managing servers - the cloud provider handles scaling and execution.</p><h3>Benefits</h3><ul><li>No server management</li><li>Automatic scaling</li><li>Pay per execution</li><li>High availability</li></ul><h3>Use Cases</h3><ul><li>Web APIs</li><li>Data processing</li><li>Real-time file processing</li><li>IoT backends</li></ul><h2>Cloud Architecture Patterns</h2><ul><li>Microservices</li><li>Event-driven architecture</li><li> CQRS (Command Query Responsibility Segregation)</li><li> Circuit breaker</li></ul>', 55, 3),

-- Course 21: DevOps Fundamentals
(21, 'Introduction to DevOps', 'Bridging development and operations', 'article', '<h2>What is DevOps?</h2><p>Culture and practice that unifies software development (Dev) and IT operations (Ops).</p><h3>Core Goals</h3><ul><li>Faster software delivery</li><li>Improved quality</li><li>Better collaboration</li><li>Continuous improvement</li></ul><h3>DevOps Lifecycle</h3><ol><li>Plan</li><li>Develop</li><li>Build</li><li>Test</li><li>Deploy</li><li>Operate</li><li>Monitor</li></ol>', 35, 1),
(21, 'CI/CD Pipelines', 'Continuous Integration and Continuous Deployment', 'article', '<h2>Continuous Integration (CI)</h2><p>Automatically build and test code changes whenever they are committed.</p><h3>CI Best Practices</h3><ul><li>Commit frequently</li><li>Automate builds</li><li>Automate tests</li><li>Fix broken builds immediately</li></ul><h2>Continuous Deployment/Delivery (CD)</h2><p>Automatically deploy validated code changes to production/staging.</p><h3>Tools</h3><ul><li>Jenkins</li><li>GitHub Actions</li><li>GitLab CI</li><li>CircleCI</li></ul><pre># GitHub Actions example\n- name: Run tests\n  run: npm test\n- name: Deploy\n  run: npm run deploy</pre>', 50, 2),
(21, 'Containerization with Docker', 'Packaging applications in containers', 'article', '<h2>What are Containers?</h2><p>Lightweight, standalone packages containing everything needed to run software.</p><h3>Containers vs VMs</h3><ul><li>Containers share OS kernel - smaller, faster</li><li>VMs include full OS - more isolation</li></ul><h2>Docker</h2><p>Platform for developing, shipping, and running containers.</p><h3>Dockerfile</h3><pre>FROM node:16-alpine\nWORKDIR /app\nCOPY package.json .\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]</pre><h3>Docker Commands</h3><pre>docker build -t myapp .\ndocker run -p 3000:3000 myapp\ndocker-compose up</pre>', 55, 3),

-- Course 22: Artificial Intelligence
(22, 'Introduction to AI', 'History and concepts of artificial intelligence', 'article', '<h2>What is Artificial Intelligence?</h2><p>The simulation of human intelligence in machines programmed to think and learn like humans.</p><h3>History</h3><ul><li>1950 - Alan Turing proposes the Turing Test</li><li>1956 - Dartmouth Conference - AI term coined</li><li>1997 - Deep Blue beats chess champion</li><li>2011 - Watson wins Jeopardy</li><li>2020s - Large Language Models emerge</li></ul><h3>Types of AI</h3><ul><li><strong>Narrow AI</strong> - Task-specific (current)</li><li><strong>General AI</strong> - Human-level intelligence (theoretical)</li><li><strong>Super AI</strong> - Surpasses human intelligence (hypothetical)</li></ul>', 40, 1),
(22, 'Neural Networks and Deep Learning', 'Building blocks of modern AI', 'article', '<h2>Neural Networks</h2><p>Computing systems inspired by biological neural networks in our brains.</p><h3>Structure</h3><ul><li><strong>Input Layer</strong> - Receives data</li><li><strong>Hidden Layers</strong> - Process information</li><li><strong>Output Layer</strong> - Produces results</li></ul><pre>class NeuralNetwork:\n    def __init__(self, layers):\n        self.weights = []\n        for i in range(len(layers) - 1):\n            self.weights.append(\n                np.random.rand(layers[i], layers[i+1])\n            )</pre><h2>Deep Learning</h2><p>Neural networks with many hidden layers.</p><h3>Types</h3><ul><li>Convolutional Neural Networks (CNN)</li><li>Recurrent Neural Networks (RNN)</li><li>Transformers (used in LLMs)</li></ul>', 55, 2),
(22, 'Natural Language Processing', 'Teaching machines to understand human language', 'article', '<h2>What is NLP?</h2><p>Branch of AI that helps computers understand, interpret, and manipulate human language.</p><h3> NLP Tasks</h3><ul><li>Text classification</li><li>Sentiment analysis</li><li>Machine translation</li><li>Question answering</li><li>Text summarization</li><li>Named entity recognition</li></ul><h2>Transformers Architecture</h2><p>Revolutionary architecture behind modern language models.</p><pre>from transformers import pipeline\n\nclassifier = pipeline("sentiment-analysis")\nresult = classifier("I love learning AI!")</pre><h3>Applications</h3><ul><li>ChatGPT and similar chatbots</li><li>Google Translate</li><li>Auto-complete in keyboards</li><li>Email spam filtering</li></ul>', 60, 3),

-- Course 23: HTML and CSS Basics (another entry)
(23, 'HTML5 Semantic Elements', 'Modern HTML structure with semantic tags', 'article', '<h2>Semantic HTML</h2><p>HTML5 introduced semantic elements that clearly describe their meaning.</p><h3>New Semantic Elements</h3><ul><li><strong><header></strong> - Page or section header</li><li><strong><nav></strong> - Navigation links</li><li><strong><main></strong> - Main content area</li><li><strong><article></strong> - Independent content</li><li><strong><section></strong> - Thematic grouping</li><li><strong><aside></strong> - Sidebar content</li><li><strong><footer></strong> - Page or section footer</li></ul><h3>Example</h3><pre><body>\n    <header><h1>My Site</h1></header>\n    <nav>...</nav>\n    <main><article>...</article></main>\n    <footer>...</footer>\n</body></pre>', 35, 1),
(23, 'CSS Variables and Animations', 'Modern CSS features for maintainability', 'article', '<h2>CSS Variables</h2><p>Custom properties that store values for reuse throughout your CSS.</p><pre>:root {\n    --primary-color: #1e3b8a;\n    --font-size: 16px;\n}\n\n.button {\n    background: var(--primary-color);\n    font-size: var(--font-size);\n}</pre><h2>CSS Animations</h2><pre>@keyframes slideIn {\n    from {\n        transform: translateX(-100%);\n    }\n    to {\n        transform: translateX(0);\n    }\n}\n\n.element {\n    animation: slideIn 0.5s ease-in-out;\n}</pre><h3>Transition Property</h3><pre>.button:hover {\n    transform: scale(1.1);\n    transition: transform 0.3s ease;\n}</pre>', 45, 2),
(23, 'Responsive Design with Media Queries', 'Creating mobile-friendly layouts', 'article', '<h2>Responsive Design</h2><p>Approach that makes web pages render well on all devices and screen sizes.</p><h3>Mobile-First Approach</h3><pre>/* Base styles for mobile */\n.container {\n    width: 100%;\n    padding: 10px;\n}\n\n/* Tablet */\n@media (min-width: 768px) {\n    .container {\n        width: 750px;\n        margin: 0 auto;\n    }\n}\n\n/* Desktop */\n@media (min-width: 1024px) {\n    .container {\n        width: 970px;\n    }\n}</pre><h3>Common Breakpoints</h3><ul><li>320px - Small mobile</li><li>768px - Tablets</li><li>1024px - Small laptops</li><li>1200px - Desktops</li></ul>', 50, 3),

-- Course 24: Java Programming
(24, 'Java Fundamentals', 'Introduction to Java programming', 'article', '<h2>Why Java?</h2><p>Java is a versatile, object-oriented language known for "Write Once, Run Anywhere" capability.</p><h3>Key Features</h3><ul><li>Platform independent (JVM)</li><li>Object-oriented</li><li>Strongly typed</li><li>Automatic memory management</li><li>Rich standard library</li></ul><h3>Your First Java Program</h3><pre>public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}</pre>', 30, 1),
(24, 'Object-Oriented Programming in Java', 'Classes, objects, and OOP principles', 'article', '<h2>Classes and Objects</h2><pre>public class Car {\n    private String brand;\n    private int year;\n    \n    public Car(String brand, int year) {\n        this.brand = brand;\n        this.year = year;\n    }\n    \n    public void drive() {\n        System.out.println(brand + " is driving");\n    }\n}\n\nCar myCar = new Car("Toyota", 2023);\nmyCar.drive();</pre><h3>OOP Principles</h3><ul><li><strong>Encapsulation</strong> - Bundling data with methods</li><li><strong>Inheritance</strong> - Extending classes (extends keyword)</li><li><strong>Polymorphism</strong> - Method overriding</li><li><strong>Abstraction</strong> - Abstract classes and interfaces</li></ul>', 50, 2),
(24, 'Java Collections Framework', 'Working with collections in Java', 'article', '<h2>Collections Framework</h2><p>Unified architecture for representing and manipulating collections.</p><h3>Main Interfaces</h3><ul><li><strong>List</strong> - Ordered, allows duplicates (ArrayList, LinkedList)</li><li><strong>Set</strong> - No duplicates (HashSet, TreeSet)</li><li><strong>Map</strong> - Key-value pairs (HashMap, TreeMap)</li><li><strong>Queue</strong> - FIFO (PriorityQueue, LinkedList)</li></ul><h3>Examples</h3><pre>// List\nList<String> names = new ArrayList<>();\nnames.add("Alice");\nnames.add("Bob");\n\n// Map\nMap<Integer, String> users = new HashMap<>();\nusers.put(1, "Alice");\nusers.put(2, "Bob");\n\n// Iterating\nfor (String name : names) {\n    System.out.println(name);\n}</pre>', 55, 3);